name: CI Express

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-shared-ci:
    uses: meditrack-yca/meditrack-actions.github/workflows/shared.yml@main
    with:
      node-version: '22.x'
      test-command: 'npm test'
      run-build: false
      target-env: 'staging'
    secrets: inherit